### ISSUE TITLE
Can you share the custom dataset and corresponding annotation json files to train this model?

### ISSUE THREAD

**Issue by SamihaSara** [ppriyank/Pytorch-CustomDataset-FasterRCNN#2]

**Comment by ppriyank** [comment]
Hello 

Just take any image and label it. I don't think I have the original dataset here with me. Annotations are pretty standard but for your custom annotations : 
i-th bounding box in the j-th image, you TRAIN_objects.json file would have 

[{...} , {....} , {boxes:  [[...] , [...] , [xmin, ymin, xmax, ymax] ....] , "labels" : [ 1,1,.... 2 ]   } , {....} , {....}]


I trained only on 17 when I created this repo
